var COVERS = {
  "PLP":     "js/PLP.png",
  "PLN":     "js/PLN.png",
  "MLP":     "js/MLP.png",
  "MLI":     "js/MLI.png",
  "GLE":     "js/GLE.png",
  "PLE":     "js/PLE.png",
  "VLS":     "js/VLS.png",
  "PLI":     "js/PLI.png",
  "LCX":     "js/LCX.png",
  "MPE":     "js/MPE.png",
  "LCC":     "js/LCC.png",
  "MPED":    "js/MPED.png",
  "EVITECH": "js/EVITECH.png",
  "VRS":     "js/VRS.png",
};
